### PR TITLE
loop prevention in breadcrumb

### PR DESCRIPTION
**Pull request by bart-j**
The breadcrumb gets in an infinite loop when object containers are referring to each other. This fix prevents this from happening.

### CODE REVIEW

**Comment by jdalsem** [comment]
What is causing the pages to be container of itself? Is it legacy? That is the better question and should also be prevented as it potentially cause more problems. 

Adding the title is no longer best practice as in Elgg 2.0 and higher this will be stripped. I have no problem in adding this now.

**Comment by bart-j** [comment]
Not sure what that is, but agree this should also be fixed. In my specific case it appears as the following:

Page 1 -> Container 1 -> Container 2 -> Container 1

so the container of 2 is again contained by 1. Probably a check should be made when changing the container of a page to see of one the parents of the container already refers to the page itself. In that case it should not be saved. 

Adding the title at the end of the breadcrumb already was in the code, only forgot to add it in my changes.

**Comment by jdalsem** [comment]
> Adding the title at the end of the breadcrumb already was in the code, only forgot to add it in my changes.

Then the commits should be squashed

**Comment by bart-j** [comment]
Not a fan of this as it breaks the commit history, but squashed it anyway in the branch.

**Comment by jdalsem** [comment]
> Not a fan of this as it breaks the commit history, but squashed it anyway in the branch.

no need to squash it in your branch, if you need to keep it there... however i am also concerned about commit history, and i want to keep it clean. Best practice is to create a special branch for each PR. That way you can keep whatever you need in your branch

**Pull request merged**
